[gcp_service_account]
type = "service_account"
project_id = "sparkanalyticsdemo"
private_key_id = "c6d971b643ad31059af4d52ed8c22a703134a202"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCwcW90J9G2eY0t
zwBaDfaS4INuD4I2rU3QsC7Ot/J7z5D0gzeBxhFvGIUIvxo10zZFxZvhOngYBLEC
6xSJNfdFyBc9DdqDlb/MYsMN3f+2Nyi/2+dI+dYkeyUDp9KG7d9AIqiVO1mKEyV+
QmoTZucuaDRf7kJX0ElMDyerk4QDcnfSrNfQMArPDYCF81kYdPNBbKBm1sH6Vd1Z
jTMy7oj7D44GqVcg10hR2rT08twDndFYIYZlQuJV65Q3aqGcmp9uEvG/YYVQeKN0
vGWGFX5p5WBVcERA07AYs9feywtQTauubj0dtaRrNAkBQ4imWs8gpVXgoTJy733e
ECK+kmLnAgMBAAECggEANcFRietpvnS42Oh0fHs9kJD7KchqzPqutvI+SHeNVkAu
MvhZLF3qSNUJDtmeBCEFq2shaxSTqwme3js9pfH9lFJ6Ff1HAgjZBs1eDLcCZYLX
lOBLzhVjsviblcoG31nQRutoPhL3XBQqO5XDWIbkzuQrdMCTkMph0lzZorHOKfgv
Xqu3VTYiaGeva4Im6dFJ6AyyheZQUBuC9gshE8TAkUDNp7a5lQbrcUia4EnDWjwh
k+mTe2MZeclq/Ozy/XBBuH58Tfs1IBG6VpnzJfHNF0Z2nXaRok8GFu98GBQJLDoy
dOJ9GmXOiFBgCnPWOf2UJU2Zjj1lCk0Rr/42abvjoQKBgQDn/RLh5R4+sWxwmnGC
ecQYanpg8fYRU/RdPLAduDTfSZj7I7HW2Zb3eDw/0Mcipmxihp2GD+OR7o/xAUeB
2+ACR4QVCLRsovCp50FkzIR7CgK9upD4Im4Hu8BrsZByvg+70kCpm1Bamc77INlj
bX4zEU58Ljepa0l2wRiYe87dYQKBgQDCtJdnFoJUc9Bc5CWQLdiwNDIPNunhXBbN
OGwWMTpzRbt9ieJ9QxWQILuREwHpVEal/r3NR2IPRARVJL1AiErFJNzsAOzX6bx8
gco+JcLZjMdsSaiecMrTqwunn2VkDroxpWE3AP1aGYRIY78ftGYwT0vJiZok8WOZ
kM9t5n8dRwKBgG15yQJfDBHLyn+s8mn/KmHXRZ8gL93nf4bMT9QGjLTeV1oUcyUP
k6V+0PfQf1jDrpwkKIwOTXcdXEIAN415hFGvDA6dB//IOMgFAKAfv1kM1VRRiX3/
SWtO17Q6nA750BTzWF5xk87djIaH7u5zyj0xKpeBe/TwUz++SewTaQChAoGABion
nQj2aWwdTcOfeNgqwzFz4E1xzEPZKPg/W9iFLD8p94iVFjg4h46xwZ8jcVrMvda5
9bTr4uXZaUS3hUKLc4B+Si6hURjCcgK9/4e8ipzNd51BbHrPwTHqNY1zbV6WAJpm
4JH0c5TZPl2CIKPalG7+TExCCCdoauVN3AHvRmMCgYAOGDk1qYrVdSYAzCvAZR7A
/qVycRKNIEjuGfCQpQRQ4FrtrV8RE1pAt5DKuDdATZ+prw3VOuu2bQqx4tpyJ38F
5Y71qMJab8WEB2pqQkmf2l5Q47Ewt7Wob2xxI4juJaGNbJZxq2sKV5Li2VqtCbyy
hHLC8Ctl+/qA3j7yenkSkw==
-----END PRIVATE KEY-----"""
client_email = "streamlit-bq-reader@sparkanalyticsdemo.iam.gserviceaccount.com"
client_id = "114808723553347709130"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bq-reader@sparkanalyticsdemo.iam.gserviceaccount.com"
